# Generated by Django 2.1.7 on 2019-03-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rooms', models.IntegerField()),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('short_desc', models.TextField(max_length=512)),
                ('long_desc', models.TextField(max_length=2048)),
                ('price', models.IntegerField()),
                ('free_rooms', models.IntegerField()),
                ('photo1', models.ImageField(default='null', upload_to='trips')),
                ('photo2', models.ImageField(default='null', upload_to='trips')),
                ('photo3', models.ImageField(default='null', upload_to='trips')),
                ('photo4', models.ImageField(default='null', upload_to='trips')),
                ('photo5', models.ImageField(default='null', upload_to='trips')),
                ('photo6', models.ImageField(default='null', upload_to='trips')),
                ('photo7', models.ImageField(default='null', upload_to='trips')),
                ('photo8', models.ImageField(default='null', upload_to='trips')),
                ('photo9', models.ImageField(default='null', upload_to='trips')),
                ('photo10', models.ImageField(default='null', upload_to='trips')),
                ('cropping', image_cropping.fields.ImageRatioField('photo1', '420x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hotel')),
            ],
            options={
                'ordering': ('departure_date',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trip'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
