# Generated by Django 2.1.7 on 2019-03-18 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('907da8a0-66b9-42e4-bc89-6716fa90dcf2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
