# Generated by Django 2.1.7 on 2019-03-18 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190318_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photos',
        ),
        migrations.AddField(
            model_name='trip',
            name='photo1',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo2',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo3',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo4',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo5',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo6',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo7',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo8',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='trip',
            name='photo9',
            field=models.ImageField(default='null', upload_to='hotels'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5acbfd08-cef7-4031-b3cd-42b8c8527ec1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
