# Generated by Django 2.1.7 on 2019-03-22 18:29

from django.db import migrations, models
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190318_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x280', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('518e65c5-042b-47bd-9fbc-9ac0aa595757'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='long_desc',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo1',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo2',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo3',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo4',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo5',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo6',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo7',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo8',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo9',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='short_desc',
            field=models.TextField(max_length=512),
        ),
    ]
