# Generated by Django 2.1.7 on 2019-03-22 20:06

from django.db import migrations, models
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190322_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.IntegerField(default=3410),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('018c058a-bdd0-4cd2-a687-8b1fb6082bfa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo1', '420x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
