# Generated by Django 2.1.7 on 2019-03-25 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190322_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='free_rooms',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('03581a02-2941-4e48-8934-8af6b0baf266'), editable=False, primary_key=True, serialize=False),
        ),
    ]
