# Generated by Django 2.1.7 on 2019-03-25 12:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190325_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('departure_date',)},
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9f0c343-86de-4bfe-9bd1-d1f0d878627e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
