# Generated by Django 2.1.7 on 2019-03-25 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190325_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28309f83-9e57-40ad-8b35-345b65f9ccb8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
