# Generated by Django 2.1.7 on 2019-03-29 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190329_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45ef6d1d-1a2a-4658-a7d8-f5546dec6bc4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
