# Generated by Django 2.1.7 on 2019-03-29 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190329_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8e5f867-3c52-4af9-b087-a7ba9ea0b9f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
