# Generated by Django 2.1.7 on 2019-03-30 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190330_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('203acb84-e13e-4003-b830-6f84d0a6de85'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo10',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo2',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo3',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo4',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo5',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo6',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo7',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo8',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo9',
            field=models.ImageField(default='null', upload_to='trips'),
        ),
    ]
